### ISSUE TITLE
Images won't embed

### ISSUE THREAD

**Issue by cambronjay** [guigrpa/docx-templates#127]
I have tried embedding an image and it does not seem to work. I even used the example code. Can anyone help me out?

**Comment by jjhbw** [comment]
What have you tried exactly? What kind of error do you get?

**Comment by ku3b1k0** [comment]
For embedding images, both the below examples work perfectly fine for me.
1.
```
+++HTML `
<body><img src="http://www.gstatic.com/webp/gallery/1.jpg"/></body>
`+++
```

2.
`+++IMAGE youCanNameThisAnythingFunction('http://www.gstatic.com/webp/gallery/1.jpg')+++`

and then in your createMethod function call, you will need something similar to this.

```
createReport({
  template,
  additionalJsContext: {
    youCanNameThisAnythingFunction: async url => {
      const resp = await fetch(url);
      const buffer = resp.arrayBuffer
        ? await resp.arrayBuffer()
        : await resp.buffer();
      return { width: 14, height: 10, data: buffer, extension: ".jpg" };
    }
  }
})
```

Note that the author of the library had clarified in #126 that image embeds by giving just the path to the image in the local filesystem is no longer supported, I believe you might need a web server running on your system, drop your image somewhere inside the docroot and can then reference the image using the localhost url, which seems to be working fine again for me.

**Comment by jjhbw** [comment]
Thanks for clarifying @ku3b1k0 !

Yes, that is indeed the case. As @ku3b1k0 pointed out in #126 , i forgot to update the example projects to reflect the fact that simply providing the image `path` is no longer supported. 

You can still read an image from a path on your local filesystem from inside the template in the way @ku3b1k0 mentions in his second example. Just write a function that performs the actual filesystem interaction instead of a `fetch` call.

Does this solve your problem?

**Comment by cambronjay** [comment]
What is not working for me is embedding via base64 string and there is no error. It executes and fills in the variables but not the base64 string image. Any suggestions?

**Comment by jjhbw** [comment]
How are you creating the base64 string? docx-templates can't really check if it is a valid image beforehand. Any chance we can see some code? I can't debug it like this.

**Comment by cambronjay** [comment]
@jjhbw I am creating it on the front end and sending it to my server. I have also tried creating it with   fs.readFileSync().
// Current code
      await createReport({
            template,
            data: {
                name: object.metadata.name,
            },
            additionalJsContext: {
                imageTest: async () => {
                     const data = base64String.slice('data:image/png;base64,'.length);
                     return { width: 300, height: 150, data: data, extension: '.png' };
                 },
            },
            noSandbox: true
        }).then(rendered => fs.writeFileSync(tempLocalTemplateFile, rendered))
            .catch((error) => {
                console.log(error)
                return null;
            })

**Comment by jjhbw** [comment]
This doesnt show the creation of the base64 string. I cant know if it is valid.

Also, what does the template look like?

**Comment by cambronjay** [comment]
@jjhbw the base64 string is created on the front end through canvas using canvas.toDataURL();. It's a valid base 64 string. The template is using +++IMAGE imageTest()+++ 
Is there something I am missing? Everything else works except the embedding of the image.
[testDoc.docx](https://github.com/guigrpa/docx-templates/files/4703674/testDoc.docx)

**Comment by cambronjay** [comment]
@jjhbw I even tried the fetch method @ku3b1k0 suggested and it does not work either. Is there something I am missing with embedding an image into the a docx? The image never gets embedded. @ku3b1k0  what version of this module are you using? I am using 4.1.0

**Comment by cambronjay** [comment]
@jjhbw The only way that it worked for me was using the svg code example. I used a base64 buffer instead.      
...               
const b64 = base64Signature.slice('data:image/png;base64,'.length);
const svg_data = Buffer.from(b64, 'base64');
return { width: 6, height: 6, data: svg_data, extension: '.png' };
.....

**Comment by jjhbw** [comment]
I think i see the problem: note the `width` and `height` params reflect the desired dimensions of the image in the rendered document _in centimeters_. I think the image is properly embedded by docx-templates, but that Word refuses to render it due to its dimensions being insanely huge...

Note that you are providing 'sane' dimensions in the svg example.

I have added a bit more emphasis on this behaviour to the README in 3a65b497608417296a492eda9421f26f6922b2d7

It is nontrivial for the library to warn or throw if the user provides image dimensions that don't make sense, as AFAIK Word documents can take arbitrary shapes. I'll look into it.

Feel free to re-open if this doesn't solve your issue.
