### ISSUE TITLE
Add empty row in end of table

### ISSUE THREAD

**Issue by Dertosh** [guigrpa/docx-templates#139]
I have problem with table generation. When generate table, generator add empty raw in table.
`
this.workList = [
            {
                startDate: "01.03",
                workName: "some work1",
                endDate: "02.04",
                result: "secsses"
            },
            {
                startDate: "01.03",
                workName: "some work2",
                endDate: "02.04",
                result: "secsses"
            },
            {
                startDate: "01.03",
                workName: "some work3",
                endDate: "02.04",
                result: "secsses"
            },
            {
                startDate: "01.03",
                workName: "some work4",
                endDate: "02.04",
                result: "secsses"
            }
        ];
await createReport({
            template: this.template,
            data: {
                workList: this.workList
            },
        });
`

[sample.docx](https://github.com/guigrpa/docx-templates/files/4907202/sample.docx)

example https://github.com/Dertosh/worgGenTest

**Comment by jjhbw** [comment]
Thanks for this comprehensive report and sorry for the late reply.

I think the problem is somewhere in the template. 

First, my Word (2016) opens the template in compatibility mode, indicating it was made with an older version of Word or possibly non-Word software (correct me if i'm wrong).

I was able to fix it by making a completely new template document in Word 2016, and manually recreating the table (see attachment).

[sample.docx](https://github.com/guigrpa/docx-templates/files/5029548/sample.docx)

i'm sorry if this isn't a satisfying answer. The docx spec is huge and there are a lot of different Word versions (and other software) that create slightly wrong documents.

Be sure to reopen this issue if the problem persists.

**Comment by Dertosh** [comment]
Thank you for solution. It help and worked.
