### ISSUE TITLE
Problem accessing images in browser using Angular compiler (Undefined Buffer)

### ISSUE THREAD

**Issue by tentone** [guigrpa/docx-templates#188]
Hello

I am using the library with Angular and typescript and since version 5.4.1 (worked well on 5.4.0) i have been getting the error:

`"Error executing command 'IMAGE $row'. Buffer is not defined" `

when using images in documents.

I believe that this should be some confusion I'm passing the image data as ArrayBuffer (also fails if base64 is used).

We are passing image data on the jx context object with each image represented using the type.

`export type DocxImage = {data: ArrayBuffer, extension: string, width: number, height: number};`

In our template we cycle our image array and present each one using:

`{{FOR row IN photos}}{{IMAGE $row}}{{END-FOR row}}`

Thanks a lot for the great job with this lib, it has been a lifesaver.

**Comment by tentone** [comment]
Well I have fixed it temporarily in my project by setting Buffer  as ArrayBuffer, seems to fix the problem.

`window.Buffer = window.ArrayBuffer`

**Comment by jjhbw** [comment]
Thanks for your report. This seems like a polyfilling issue that testing doesn't pick up because webpack polyfills/shims stuff like this more aggressively than the Angular compiler. It seems we already discussed a similar issue a while ago #135 .

I'll add it to my backlog. I think we may be able to reduce our reliance on types like Buffer that aren't portable between browser/node versions.

**Comment by jjhbw** [comment]
https://github.com/guigrpa/docx-templates/releases/tag/v4.8.0 may help with this, as it contains a precompiled polyfilled build. LMK if you run into any issues.
