### ISSUE TITLE
Warning: Unreachable document generated using docx-template

### ISSUE THREAD

**Issue by ni3galave** [guigrpa/docx-templates#206]
I am generating Docx file using docx-template through the nodeJs environment And using the LibreOffice tool for the edit/view operation of the template that used to generate the final docx file. The template file contains images, tables, and many more. Also, I am able to generate docx file without any error.

Problem Statement: 
When I open a successfully generated file in Microsoft word, it shows a warning popup `"Word found unreachable content in the file"`. See attached image for more information. I am able to open file If I say "Yes" on popup :)

I want to understand what is this warning and how can I get rid of it.

<img width="435" alt="Screenshot 2021-04-28 at 1 56 34 AM" src="https://user-images.githubusercontent.com/3500159/116309899-fb839580-a7c6-11eb-92c6-8e651301525e.png">

Code Sample : 
```
const report = await createReport({
    template: template,
    noSandbox:true,
    additionalJsContext: {
      getImage: url => {
        const data = url.slice('data:image/png;base64,'.length);
        return {
          width: 20,
          height: 10,
          data :data,
          extension: '.png'
        };
      }
    },
    data
  });

```

Sample Template:
[sample_docx_template.docx](https://github.com/guigrpa/docx-templates/files/6405112/sample_docx_template.docx)

**Comment by jjhbw** [comment]
Docx documents are complex, and there are many things that can go wrong. Please provide a minimal code example and a template so i can reproduce the problem.

**Comment by ni3galave** [comment]
@jjhbw I have updated the Issue with sample code and template.

**Comment by ni3galave** [comment]
@jjhbw I found the root cause of it. This is due to the Bottom borderline in the Header and footer section[See Sample doc]. If I remove these two lines from the template then the document opens without any warning. But still, I am not able to figure out why this is happening.

**Comment by ni3galave** [comment]
I am able to solve this issue by recreating the header and footer sections in the MS office.

**Comment by jjhbw** [comment]
Thanks for posting your solution! Sorry i couldn't be of more help.

**Comment by oscardianno** [comment]
In case someone else comes across this in the future, indeed try deleting any kind of forms and figures created in Word first. In my case, the warning was caused by figures like this:
![image](https://user-images.githubusercontent.com/46467428/207462857-ee4692ff-fd85-40dc-8ac6-451b21b83aa4.png)
![image](https://user-images.githubusercontent.com/46467428/207463381-9803d74a-7856-4dd3-a3d0-2575f118990d.png)
It wasn't until I removed those that I was able to generate the document without getting the warning on open.
I had done a very long template already so I had to make a lot of tries removing stuff to see what was causing the issue, so I hope that it may help someone in a similar situation.

Thanks for posting your solution and thanks for the great tool! ^^
