### ISSUE TITLE
I want to contribute to by adding some styling to template

### ISSUE THREAD

**Issue by DVGY** [guigrpa/docx-templates#215]
I am an absolute begineer. How should I get started. What documentation shall I read? Please guide me right direction Thanks

**Comment by jjhbw** [comment]
Hi @DVGY , what exactly do you want to contribute?

If you want to know more about the docx file format, I suggest reading about the Office Open XML(also known as OpenXML or OOXML) specification [here](http://officeopenxml.com).

**Comment by DVGY** [comment]
> docx file form

One of main thing which I always wanted want to put background color to table cell, change text color according to text value.
I suppose this is not yet available right ?

**Comment by jjhbw** [comment]
No, docx-templates doesn't offer an out-of-the-box way to do that. It does allow you to insert literal XML, though, which may help with this. The user is responsible for making sure the XML is valid and functional.

**Comment by DVGY** [comment]
> No, docx-templates doesn't offer an out-of-the-box way to do that. It does allow you to insert literal XML, though, which may help with this. The user is responsible for making sure the XML is valid and functional.

@jjhbw Can you please point me out to the exact open xml page where all this styling is described ?

**Comment by davidjb** [comment]
As an example, setting the cell's background can be done with the following literal XML and standard delimiters:

```xml
||<w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="00FF00"/></w:tcPr>||
```

Likewise, setting the foreground text color can be done with:

```xml
||<w:rPr><w:color w:val="00FF00"/></w:rPr>||
```

Either of these strings could either be attached to your `data` object and referred to directly in your template (e.g. `{{ validBg }}` if set as the `validBg` property), or else returned as part of a result of an `additionalJsContext` function (which could, for example, take arguments to make the color change based on other variables), for example:

```js
const report = await createReport({
  // ...
  additionalJsContext: {
    styledBg: (value) => {
      let color = value < 100 ? '00FF00' : 'FF0000';
      return `||<w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="${color}"/></w:tcPr>||`
    }
  }
})
```

Then, in your template, if you write `{{ styledBg(value) }}` inside a table cell, the background will be green if the `value` is less than 100, or red otherwise.
