### ISSUE TITLE
Metadata is returning wrong number of pages

### ISSUE THREAD

**Issue by Ademking** [guigrpa/docx-templates#240]
Thank you so much for this library. It's so helpful.

I have this bug... Metadata is returning wrong page number... the final document is 47 pages but it's showing 5

I think it's because of HTML content? Maybe?

![image](https://user-images.githubusercontent.com/12462188/134828460-57937b8a-520e-4e4a-a9ca-952351d5e131.png)

![image](https://user-images.githubusercontent.com/12462188/134828499-591dfef4-47bb-456e-bbf9-11dd28986e7f.png)

- Runtime environment; NodeJs
- Version: 4.8.0

I'm using HTML content inside a FOR Loop... example
```
+++HTML `
<body>
  ${$t.code}
</body>
`+++
```

**Comment by mathe42** [comment]
Is your template document 5 pages long?

**Comment by jjhbw** [comment]
The number of pages is simply grabbed from a docx XML metadata element. It can only feasibly be determined by a docx renderer, like MS Word or LibreOffice.
The document needs to be rendered by e.g. Word at least once before the length of the document can be known. Word will update the 'number of pages' metadata element when saving the document. You are probably looking at the number of pages of your template because the metadata hasn't been updated yet, like @mathe42 says.

In more technical terms: I don't think the length of the document can be determined just by static analysis of the docx XML; the XML needs to be rendered. The `pages` metadata is just a reflection of that.

**Comment by Ademking** [comment]
@mathe42: Yes. It's 5 pages

@jjhbw: I get it now... So i can't get the exact number using metadata
Thank you guys for the help 👍👍
Keep up the good work

**Comment by jjhbw** [comment]
👍 Great. Yes, this seems to be a hard limitation. Sorry I couldn't give a more satisfying answer.
