### ISSUE TITLE
Error: Can't read the data of 'the loaded zip file'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?

### ISSUE THREAD

**Issue by sealover06** [guigrpa/docx-templates#248]
Hello team, I'm testing this package for first time
node --version
v16.5.0

my little code, basically a copy/paste of the readme. 

```
const
  createReport = require('docx-templates').default,
  fs = require('fs');

async function main() { 
  let
    docx = fs.readFileSync('hello.docx'),
    data = { fn: 'Thats', ln: 'me' };
  const buffer = await createReport({ docx, data: data } );
  fs.writeFileSync('output.docx', buffer);
}	
 main();
 // docx file contains only the the following line: 
 // Hello +++= `${fn} ${ln}`+++
 // expecting therefore Hello Thats me
```
I'm getting this error in jszip library. No clue what we get into this.  
![image](https://user-images.githubusercontent.com/47537190/142691932-76e1c85c-7beb-43d2-8edb-fd7640b44a06.png)

Thanks for telling me what I'm doing wrong.

**Comment by jjhbw** [comment]
See this line:

```javascript
await createReport({ docx, data: data } );
```

You are providing the template as an object property named 'docx', but it needs to be called `template`, like so:

```javascript
await createReport({ template: docx, data: data } );
```

I strongly recommend using typescript (with strictest settings) instead of javascript if you can. It prevents errors like this, because it would tell you the `template` argument is missing.

I agree that the error is confusing. I'll make it a bit more clear. Hope this helps!

**Comment by sealover06** [comment]
OMG, I had to be tired this day.  ! thank you  !
