### ISSUE TITLE
Feature: single-line delimiter

### ISSUE THREAD

**Issue by jcalfee** [guigrpa/docx-templates#255]
Many programming languages have single and multi-line comments which help keep the code clean.  I propose something similar for templates which offer backwards compatibility.

```js
await docx.createReport({
   cmdDelimiter: ['+++, '+++'],
   cmdDelimiterSingleLine: ['{', '}'],
   ...
})
```
1. cmdDelimiter is single or multi-line
2. Ignore cmdDelimiterSingleLine if within cmdDelimiter
3. Break out of cmdDelimiterSingleLine if you hit a newline
4. In the rare case you want to print { and } on the same line: `+++= '{'+++ ... +++= '}'+++`

**Comment by jjhbw** [comment]
I took a peek in the backend to see what kind of changes this feature would entail, and it is not trivial. I'm not sure about the value-add yet... How would this improve the code in template? A command can already span multiple lines.

**Comment by jcalfee** [comment]
I was hoping that would be trivial.  It would be good for {templates} with {lots} of simple {variables}.  Even IF and FOR are single line statements.  It is one thing that stands out when choosing libraries, the ability to keep it short but have plenty of control with larger blocks so you know your not going to get into a situation you can design for.  Best of both worlds.

**Comment by jjhbw** [comment]
New features always have a maintenance burden attached for any project, but for this library in particular. This is mostly because the docx file specification is so complex that even our extensive set of snapshot tests can't do it justice. 

Because of this, any feature requests that require changes to the core of the library have to offer extremely obvious added value for me to consider them. Convenience changes to the API don't fit in this category IMO. Thanks for the suggestion but I'm going to have to reject it. I hope you understand.

**Comment by jcalfee** [comment]
Of course I understand.  I was thinking I might try this later with some code to pre-process the template.  Since it is all in memory this **should** be very fast.  Unless of course that approach suffers the same concerns.

**Comment by jjhbw** [comment]
Yes, all template processing happens in memory so speed is not really my concern. Complexity is.

All software projects suffer from feature creep to some extent, but open source projects more so because maintainers tend to feel pressured to accept outside contributions ("they went through all that effort, you know?"). It is not uncommon for such projects to collapse under their weight, or worse; see the news about Log4j recently.

Just making sure you know why I'm rejecting what may well be a good feature.
