### ISSUE TITLE
Question: How to append formatted content in template.

### ISSUE THREAD

**Issue by nathan130200** [guigrpa/docx-templates#264]
How to proper append formatted content into template and render in docx?

For example i have an dynamic field that i must make it bold.

`<b>ID:</b> 000000000` as usually in HTML, but html don't display in libreoffice, so have some work-around to append direct bold text into DOCX as teimplated?

I cannot pre-format as bold, becasuse this field is non required, so some will have others don't.

Also i'm trying to insert line breaks but \r\n, \r or \n don't works.

**Comment by jjhbw** [comment]
You can try injecting literal XML. For this you can take a look at the `literalXMLDelimiter`. See for example https://github.com/guigrpa/docx-templates/blob/306af4373a8676a4ad86c7a250305efdcbfffc97/src/__tests__/templating.test.ts#L413 . You'll have to look up the required XML elements yourself in the docx spec.

**Comment by jjhbw** [comment]
I can't really help with this information.

You can unzip the docx file and inspect the XML files to see if the elements are inserted in the way you'd expect.

Otherwise you can look into whether libreoffice competitors (MS Word, Google Docs) render the element correctly. In that case the problem may be libreoffice-specific.
