### ISSUE TITLE
Feature request: template as Buffer, output as Buffer

### ISSUE THREAD

**Issue by saknarak** [guigrpa/docx-templates#28]
It wold be nice if template support node Buffer and also output as node Buffer

something like this
```
let template = fs.readFileSync('./template.docx')
let report = await createReport({
    template,
    data: {id: 1},
    nodeBuffer: true, // or something else
  })
console.log('Is buffer?', report instanceof Buffer)
```

I try to make PR, but my laptop is Windows, some build tools are not working

**Comment by vdechef** [comment]
I would also like to have this. I will create a PR.
The problem is having a neat API, without breaking existing ones.
@guigrpa : maybe we could check the type of given `template` param, and use buffer if it is not a `File` ?

**Comment by josduj** [comment]
@saknarak 
Until this is implemeted/published, this might help you:

```javascript
const { default: createReport } = require('docx-templates/lib/mainBrowser')
const { readFile } = require('fs')
const { promisify } = require('util')

const readFileAsync = promisify(readFile)

async function generateDocx(data) {
    const template = await readFileAsync('./template.docx')
    return createReport({ template, data })
}

module.exports = {
    generateDocx,
}
```

It returns `Uint8Array`, but you can convert it easily to node buffer with `Buffer.from()` (but it shouldn't really be a problem since `Buffer` instances are also `Uint8Array` instances).

@guigrpa @vdechef 
I'm also interested in having this feature, so if you need any help I'm available.
I like the idea of outputting buffer if no output path is specified, but that would be a breaking change. Determining output type from template type doesn't cover the case where we would have file path as input and buffer as output.
Maybe using `output: 'buffer'` could be a better option?

**Comment by koresar** [comment]
It looks fairly simple to implement.

In [this file](https://github.com/guigrpa/docx-templates/blob/master/packages/docx-templates/src/mainNode.js) instead of this:

```js
  await fs.ensureDir(path.dirname(output));
  await fs.writeFile(output, report);
  return null;
```

Have this:

```js
  return Buffer.from(report);
```

It just requires some tests and README update. Anyone keen to do it?
