### ISSUE TITLE
Insert Images

### ISSUE THREAD

**Issue by moisesrodriguez** [guigrpa/docx-templates#3]
Hey we love this project, but we are looking for a way to insert images. Which in our case the images are unique barcodes for each .docx we create. Is this something that would be doable? Willing to help out.

**Comment by guigrpa** [comment]
I'm not sure I understand your use case. Do you mean...

* ...a single, different barcode image for each output .docx file? (in that case, it could be added to the output bundle at a pre-specified path just before zipping it; a single CLI parameter would suffice).

* ...or multiple barcodes per .docx, depending on dynamic input data? (much harder... :sweat: ).

**Comment by guigrpa** [comment]
Did I say CLI? I meant configuration parameter :)

**Comment by moisesrodriguez** [comment]
The use case I'm trying to describe is to be able to insert images dynamically into the docx, I just gave an example of a barcode (which is already dynamically created and saved in our server temporarily as a .png). Unless I'm mistaken, right now the only way to insert an image is to put it in the docx template. But that would be a hard-coded solution, I want to be able to insert them dynamically.

**Comment by guigrpa** [comment]
Ideally, we could add a new template command (let's call it tentatively `IMAGE`) that adds an image to the document. Such a command would take as arguments the image path (which may even be a variable, so that it would even support loops) and probably width and height. I will put that on the roadmap, but it may take a little while since it's not so simple: a new command, modifications to the `document.xml.rels` file (currently not processed), etc.

In the meantime, you could try this workaround:

1. Generate a template with an example image, and style it however you want.
1. Generate an output file with `docx-templates`
1. Unzip the `.docx` file (it's just an ordinary .zip file, albeit with a different extension), replace `word/media/<yourImage.png>` with the file you need (note that Word changes the filenames), and re-zip

You could turn the last step into a shell script, or alternatively add it to the JavaScript snippet in which you call docx-templates. **OR: we may add it to docx-templates as an interim solution until we have the `IMAGE` command. Would you like to have a go at this last option and submit a PR?**

**Comment by AngelMunoz** [comment]
Hi, I tried doing the last suggested workaround (unzip replace rezip) no code involved however when I tried to open the file it was marked as corrupted, does this works different working with code?
also I would like to give it a try on the work around perhaps this weekend any pointers where I could start getting my feet wet?

**Comment by guigrpa** [comment]
Take special care when you rezip -- when you open the new zipfile, you should see Word folders at the root level: `docProps`, `word`, `_rels`, etc. You should *not* see a single folder containing those. Was that the problem?

Regarding the proposed PR (thanks for volunteering!): you may want to:

* Add an extra option to `UserOptions` (see **types.js**). For example, a `replaceImages` object that maps an internal bundle path (e.g. `word/media/image2.png`) to an external, absolute image path.
* Add a processing step in **main.js**, just before the final zipping (note that this file will someday be updated to use async/await), that applies the new `replaceImages` option, copying files to the corresponding locations (you may want to check out `fs-extra`'s `copySync` utilities for that).

I hope that helps!

**Comment by guigrpa** [comment]
Closed with the integration of #5

**Comment by guigrpa** [comment]
See #14
