### ISSUE TITLE
Setting fill color for table cells

### ISSUE THREAD

**Issue by rbeeler-ha** [guigrpa/docx-templates#309]
I'd like to set the fill color for a table cell based on the value I'm writing to the cell.  Any examples of how to do this?

**Comment by jjhbw** [comment]
I don't have a simple answer for you on how to do this. You can try embedding IF-statements into the table cell, that conditionally render something colorful, but I doubt that this will enable you to change the fill color of the entire cell.

For a more flexible table experience you can look into using the `HTML` command to insert an actual HTML `<table>` element which allows for more flexible formatting using CSS. Note that the result will only work in MS Word (see #201 ).

**Comment by davidjb** [comment]
Setting the cell's fill and background can be done with the following literal XML and standard delimiters:

```xml
||<w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="00FF00"/></w:tcPr>||
```

(Ref: see Shading Class https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.shading?view=openxml-2.8.1 for other options and types of patterned shading)

Changing the cell's color based on a value needs an `additionalJsContext` function that takes that value to make the color change, for example:

```js
const report = await createReport({
  // ...
  additionalJsContext: {
    styledBg: (value) => {
      let color = value < 100 ? '00FF00' : 'FF0000';
      return `||<w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="${color}"/></w:tcPr>||`
    }
  }
})
```

In your template, if you write `{{ styledBg(value) }}` inside a table cell, the background will become green when `value` is less than 100, or red otherwise. This function can be as simple or as complex as you want to make it, and can take any number of arguments if you want to base your styling on multiple variables. It also works fine inside conditionals or loops with `$variables`.

If you're so inclined, the `styledBg` function could also output the literal text of the value itself, to avoid the template writer having to repeat themselves (e.g. `{{ styledBg(value) }}` instead of, say `{{ styledBg(value) }} {{value}}`.

**Comment by rbeeler-ha** [comment]
This did the trick - thank you very much!
