### ISSUE TITLE
Browserify example doesn't include image correctly in generated report

### ISSUE THREAD

**Issue by guigrpa** [guigrpa/docx-templates#36]
When using the Browserify Quill example, the image is not correctly included in the rendered report. Apparently, the image is included as base64 in the HTML file, so maybe base64-images are incompatible with altChunk?

@vdechef Any ideas?

**Comment by vdechef** [comment]
I will check this when I have some time, maybe next week.

**Comment by vdechef** [comment]
I did some tests, and this is troublesome. I cannot figure a way to define the image size in HTML. I tried with img attributesn inline style, or css, but Word keeps ignoring the provided size ...

**Comment by guigrpa** [comment]
Is it a problem with the size? Maybe `<img src="..." height="50" width="100"/>`? (default unit: `px`)

**Comment by vdechef** [comment]
I tried with:
- `<img src="..." height="50px" width="100px"/>`
-`<img src="..." style="width: 50px; height: 100px;">`
-`<style>#mypic {style="width: 50px; height: 100px";}</style><img src="..." id="mypic">`

Nothing worked ... I think the problem is in Microsoft HTML parser. 
Maybe MHT files are better parsed then HTML files by Word, but I did not test this.

**Comment by guigrpa** [comment]
I'm closing it, since it doesn't seem critical and I don't foresee having the time to look into this.
