### ISSUE TITLE
EXEC command examples do not work. Should use var instead of const

### ISSUE THREAD

**Issue by koresar** [guigrpa/docx-templates#41]
I have just found out that if I use `+++! const a=1;+++` command does not work. Throws `Unknown symbol 'a'`.

But as soon as I changed it to `+++! var a=1;+++` the further usage of the `a` variable works.

Is it a known thing?

**Comment by guigrpa** [comment]
`+++! const a=1;+++` works on my machine, at least within the installed docx-templates repo and from the example-node directory. What Node version are you using? I've tried with v8.11.4, v9.11.2, v10.12.0 and v11.1.0 and it consistently works.

**Comment by vdechef** [comment]
Same for me : I cannot reproduce it on my side.
@koresar could you give a full example to reproduce your problem ?

**Comment by razyon** [comment]
@guigrpa Koresar is right, if you declare your variables as **const** in +++EXEC +++ you will be able to use them only in the exec script. If you want to access these variables in other +++EXEC +++ scripts or +++INS +++ you have to declare them more globally with **var**.

`+++! const a=1;+++` is working but useless as you will never be able to access **a** in any other snippet.

To resume:
```
+++! const a='1';+++
+++= a+++
```

**does not work**

```
+++! var a='1';+++
+++= a+++
```
**works**

**Comment by guigrpa** [comment]
@razyon I see! Thanks for the clarification. I guess the original post was missing the key part: "from another EXEC block".

#48 has just been merged explaining this in the docs. It's normal that variables declared with `const` are not visible, since they are local to the block in which they're defined. Use `var` instead, or just nothing at all: `+++! a = '1'`.
