### ISSUE TITLE
Properly handling missing variable substitutions

### ISSUE THREAD

**Issue by coobr01** [guigrpa/docx-templates#55]
It there a proper and/or "suggested" way to handle situations where there are templating definitions in a .docx file but no corresponding data to fulfill it being passed in via a JSON object? 

Basically, we're getting "error:  Error: Error executing command:" & "xblankx is not defined" because our json does not contain the correct data in the INS statement. I assume we could just wrap everything up in an IF statement but if so, how can we properly check to see if a JSON object !== undefined

Example
===============================================

+++ IF outerJSONobj !== undefined && outerJSONobj.subattribute !== undefined +++
  +++INS `${outerJSONobj.subattribute}`+++
+++ END-IF +++

**Comment by guigrpa** [comment]
Hi there, and sorry for the delay.

Please try this:

```
+++ IF typeof outerJSONobj !== 'undefined' && outerJSONobj.subattribute != null +++
+++INS outerJSONobj.subattribute+++
+++ END-IF +++
```

**Comment by guigrpa** [comment]
Note that:

* To check for the existence of a variable, you cannot compare against `undefined` (since it may not exist) -- better use the `typeof` operator.
* Instead of comparing `x.subattribute !== undefined`, it's probably better to do it like this: `x.subattribute != null`, since it guards against both `null` and `undefined`.
* You can use the shorthand notation `+++= whatever +++` instead of `+++INS whatever +++`.
