### ISSUE TITLE
format the text from code

### ISSUE THREAD

**Issue by JonathanLSignot** [guigrpa/docx-templates#9]
HI there, in what way could you format the text from code? (for example, bold) and is there a possibility of creating tables from code?

**Comment by guigrpa** [comment]
Regarding formatting, you can apply the formats you want in the template (with Word). Maybe you could share an example of what you want to achieve.

Regarding tables, please have a look at the Star Wars example, which includes many data-driven tables. You can use the `FOR` command for that. And you can also wrap the whole table in an `IF` so that it only gets generated in case a given condition is met.

**Comment by JonathanLSignot** [comment]
What happens is that I'm generating paragraphs of text with different variables (what I put in the word, it's a variable with that paragraph), but I'm interested in only one part being in bold, for example: 
This is my paragraph formed by variables, **this part must appear in bold**. 

My question is whether something like this could be achieved:
This is my paragraph consisting of variables, <bold> this part should appear in bold</ bold>.

**Comment by guigrpa** [comment]
Do you mean formatting *inside* a variable's contents? No, in principle that's not possible with this library.

**Comment by vdechef** [comment]
Using EXEC, you could parse your paragraph and split it into 2 different variables. Then INS normal for the first one, and INS in bold for the second one

**Comment by guigrpa** [comment]
That'd be a nice workaround, yes. Thanks, @vdechef !
